# Generated by Django 4.2 on 2023-04-09 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dialog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="标题")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("deleted", models.BooleanField(default=False, verbose_name="删除状态")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "对话",
                "verbose_name_plural": "对话",
                "db_table": "dialog",
            },
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "source",
                    models.CharField(
                        choices=[("Quest", "Request"), ("Response", "Response")],
                        default="Quest",
                        max_length=16,
                        verbose_name="source",
                    ),
                ),
                (
                    "tokens_count",
                    models.IntegerField(default=0, verbose_name="tokens_count"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("updated", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("deleted", models.BooleanField(default=False, verbose_name="删除状态")),
                (
                    "dialog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat.dialog",
                        verbose_name="对话",
                    ),
                ),
            ],
            options={
                "verbose_name": "log",
                "verbose_name_plural": "logs",
                "db_table": "log",
            },
        ),
        migrations.AddIndex(
            model_name="log",
            index=models.Index(fields=["source"], name="chat_dialog_log_source"),
        ),
        migrations.AddIndex(
            model_name="log",
            index=models.Index(fields=["created"], name="chat_dialog_log_created"),
        ),
        migrations.AddIndex(
            model_name="dialog",
            index=models.Index(fields=["title"], name="chat_dialog_title"),
        ),
        migrations.AddIndex(
            model_name="dialog",
            index=models.Index(fields=["created"], name="chat_dialog_created"),
        ),
    ]
