# Generated by Django 4.2 on 2023-04-09 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dialog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="title")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                ("deleted", models.BooleanField(default=False, verbose_name="deleted")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "dialog",
                "verbose_name_plural": "dialogs",
                "db_table": "dialog",
            },
        ),
        migrations.CreateModel(
            name="DialogLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="content")),
                (
                    "source",
                    models.CharField(
                        choices=[("Quest", "Request"), ("Response", "Response")],
                        default="Quest",
                        max_length=16,
                        verbose_name="source",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="updated"),
                ),
                ("deleted", models.BooleanField(default=False, verbose_name="deleted")),
                (
                    "dialog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat.dialog",
                        verbose_name="dialog",
                    ),
                ),
            ],
            options={
                "verbose_name": "dialog log",
                "verbose_name_plural": "dialog logs",
                "db_table": "dialog_log",
            },
        ),
        migrations.AddIndex(
            model_name="dialoglog",
            index=models.Index(fields=["source"], name="chat_dialog_log_source"),
        ),
        migrations.AddIndex(
            model_name="dialoglog",
            index=models.Index(fields=["created"], name="chat_dialog_log_created"),
        ),
        migrations.AddIndex(
            model_name="dialog",
            index=models.Index(fields=["title"], name="chat_dialog_title"),
        ),
        migrations.AddIndex(
            model_name="dialog",
            index=models.Index(fields=["created"], name="chat_dialog_created"),
        ),
    ]
